apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-vz5q
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-vz5q@sha256:865564bbb0f88758413059b621b47cf2cc3c92984a14bf1f3be2388247e40fc8
        name: my-nodejs
        resources: {}
status: {}
